services:
  lidar:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    command: |
      /bin/bash -c "
        source /ros_entrypoint.sh &&
        source /rslidar_ws/install/setup.bash"
    # TODO
    environment:
      # Настройки для графического интерфейса (Rviz2)
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      # UNIX socket (файл) для подключения графического интерфейса
      - /tmp/.X11-unix:/tmp/.X11-unix
